/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-04-10 23:16:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>IFT287 - Menu</title>\n");
      out.write("<meta HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<meta NAME=\"author\"\n");
      out.write("\tCONTENT=\"Guillaume Harvey, Kevin Labrie, Mathieu Larocque, Vincent Philippon\">\n");
      out.write("<meta NAME=\"description\" CONTENT=\"Menu\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<center>\n");
      out.write("\t\t<h1>Menu</h1>\n");
      out.write("\t\t<form ACTION=\"Menu\" METHOD=\"POST\">\n");
      out.write("\t\t\t<input id=\"demande\" TYPE=\"hidden\" NAME=\"demande\" VALUE=\"menu\" /> \n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter un film\" onclick=\"document.getElementById('demande').value = 'ajouterFilm';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter une description a un film\" onclick=\"document.getElementById('demande').value = 'ajouterDescFilm';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter une personne\" onclick=\"document.getElementById('demande').value = 'ajouterPersonne';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter un acteur dans un film\" onclick=\"document.getElementById('demande').value = 'ajouterActeurFilm';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter une serie\" onclick=\"document.getElementById('demande').value = 'ajouterSerie';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter une description a une serie\" onclick=\"document.getElementById('demande').value = 'ajouterDescSerie';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter un un episode dans une serie\" onclick=\"document.getElementById('demande').value = 'ajouterEpisode';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Ajouter un acteur dans un episode d'une serie\" onclick=\"document.getElementById('demande').value = 'ajouterActeurSerie';\" /> <br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Supprimer un film\" onclick=\"document.getElementById('demande').value = 'supprimerFilm';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Supprimer une personne\" onclick=\"document.getElementById('demande').value = 'supprimerPersonne';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Lister les acteurs d'un film\" onclick=\"document.getElementById('demande').value = 'listerActeurFilm';\" /> <br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Lister les acteurs d'une serie\" onclick=\"document.getElementById('demande').value = 'listerActeurSerie';\" /><br/>\n");
      out.write("                        <input TYPE=\"SUBMIT\" VALUE=\"Lister les series contenant un acteur\" onclick=\"document.getElementById('demande').value = 'listerSerieActeur';\" />\n");
      out.write("\t\t</form>\n");
      out.write("\t</center>\n");
      out.write("\t<br>\n");
      out.write("\t");
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageErreur.jsp", out, false);
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t");
      out.write('\n');
      out.write('	');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\tDate et heure normale de l'est:\n");
      out.write("\t");
      out.print(DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG,
                    Locale.CANADA_FRENCH).format(new java.util.Date()));
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
