
DROP TABLE IF EXISTS Personne CASCADE;
DROP TABLE IF EXISTS Film CASCADE;
DROP TABLE IF EXISTS RoleFilm CASCADE;
DROP TABLE IF EXISTS Serie CASCADE;
DROP TABLE IF EXISTS Episode CASCADE;
DROP TABLE IF EXISTS RoleEpisode CASCADE;
