/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-04-10 16:22:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>IFT287 - Système de gestion de bibliothèque MAH BOI!</TITLE>\r\n");
      out.write("<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<META NAME=\"author\" CONTENT=\"Marc Frappier\">\r\n");
      out.write("<META NAME=\"description\"\r\n");
      out.write("CONTENT=\"page d'accueil système de gestion de bilbiothèque.\">\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<CENTER>\r\n");
      out.write("<H1>Système de gestion de bibliothèque</H1>\r\n");
      out.write("<FORM ACTION=\"Login\" METHOD=\"POST\">\r\n");
      out.write("    <BR>\r\n");
      out.write("    <BR>\r\n");
      out.write("    User Id : <INPUT TYPE=\"TEXT\" NAME=\"userIdBD\" VALUE=\"postgres\">\r\n");
      out.write("    <BR>\r\n");
      out.write("    <BR>\r\n");
      out.write("    Mot de passe : <INPUT TYPE=\"TEXT\" NAME=\"motDePasseBD\" VALUE=\"ubuntu\">\r\n");
      out.write("    <BR>\r\n");
      out.write("    <BR>\r\n");
      out.write("    Serveur : <SELECT NAME=\"serveur\">\r\n");
      out.write("                <OPTION VALUE=\"postgres\">postgres\r\n");
      out.write("              </SELECT>\r\n");
      out.write("    <BR>\r\n");
      out.write("    <BR>\r\n");
      out.write("    adresseIP : <INPUT TYPE=\"TEXT\" NAME=\"adresseIP\"  VALUE=\"127.0.0.1\">\r\n");
      out.write("\r\n");
      out.write("    <BR>\r\n");
      out.write("    <BR>\r\n");
      out.write("    BD : <INPUT TYPE=\"TEXT\" NAME=\"bd\"  VALUE=\"postgres\">\r\n");
      out.write("<BR>\r\n");
      out.write("<BR>\r\n");
      out.write("<INPUT TYPE=\"SUBMIT\" VALUE=\"Soumettre\">\r\n");
      out.write("</FORM>\r\n");
      out.write("</CENTER>\r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageErreur.jsp", out, false);
      out.write("\r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("Date et heure normale de l'est: ");
      out.print( DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, Locale.CANADA_FRENCH).format(new java.util.Date()) );
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
